Project Name: EECS 690 Mini-Project 02a

Purpose: Practice loading data in multiple formats

Input(s):   happiness_report.csv - Kaggle

            happiness_report_semicolon.csv

            happiness_report.tsv

            happiness_report_metadata.csv

            happiness_report.xlsx
            
            happiness_report_no_header.csv

Output(s):  Scatter plot of gdp vs life expectancy

            Bar chart of happiness score

Author: Jacob Kice

Initial Date: 02 / 14 / 2026

Updated Date: 02 / 14 / 2026

In [1]:
# Import libraries
import pandas as pd
import altair as alt

Load and display datasets

In [2]:
happiness = pd.read_csv("data/happiness_report.csv")    # Standard csv file
happiness

,country,happiness_score,GDP_per_capita,life_expectancy,freedom
0,Norway,7.537,1.616463,0.796667,0.635423
1,Denmark,7.522,1.482383,0.792566,0.626007
2,Iceland,7.504,1.480633,0.833552,0.627163
3,Switzerland,7.494,1.564980,0.858131,0.620071
4,Finland,7.469,1.443572,0.809158,0.617951
...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.326425,0.581844
151,Syria,3.462,0.777153,0.500533,0.081539
152,Tanzania,3.349,0.511136,0.364509,0.390018
153,Burundi,2.905,0.091623,0.151611,0.059901
154,Central African Republic,2.693,0.000000,0.018773,0.270842

In [3]:
happiness.head(10)

       country  happiness_score  GDP_per_capita  life_expectancy   freedom
0       Norway            7.537        1.616463         0.796667  0.635423
1      Denmark            7.522        1.482383         0.792566  0.626007
2      Iceland            7.504        1.480633         0.833552  0.627163
3  Switzerland            7.494        1.564980         0.858131  0.620071
4      Finland            7.469        1.443572         0.809158  0.617951
5  Netherlands            7.377        1.503945         0.810696  0.585384
6       Canada            7.316        1.479204         0.834558  0.611101
7  New Zealand            7.314        1.405706         0.816760  0.614062
8       Sweden            7.284        1.494387         0.830875  0.612924
9    Australia            7.284        1.484415         0.843887  0.601607

In [4]:
happiness_semicolon = pd.read_csv("data/happiness_report_semicolon.csv", sep=";", decimal=",")  # Semicolon seperated data, 
                                                                                                # used European style decimals
happiness_semicolon

,country,happiness_score,GDP_per_capita,life_expectancy,freedom
0,Norway,7.537,1.616463,0.796667,0.635423
1,Denmark,7.522,1.482383,0.792566,0.626007
2,Iceland,7.504,1.480633,0.833552,0.627163
3,Switzerland,7.494,1.564980,0.858131,0.620071
4,Finland,7.469,1.443572,0.809158,0.617951
...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.326425,0.581844
151,Syria,3.462,0.777153,0.500533,0.081539
152,Tanzania,3.349,0.511136,0.364509,0.390018
153,Burundi,2.905,0.091623,0.151611,0.059901
154,Central African Republic,2.693,0.000000,0.018773,0.270842

In [5]:
happiness_tab = pd.read_csv("data/happiness_report.tsv", sep="\t")  # Tab seperated values
happiness_tab

,country,happiness_score,GDP_per_capita,life_expectancy,freedom
0,Norway,7.537,1.616463,0.796667,0.635423
1,Denmark,7.522,1.482383,0.792566,0.626007
2,Iceland,7.504,1.480633,0.833552,0.627163
3,Switzerland,7.494,1.564980,0.858131,0.620071
4,Finland,7.469,1.443572,0.809158,0.617951
...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.326425,0.581844
151,Syria,3.462,0.777153,0.500533,0.081539
152,Tanzania,3.349,0.511136,0.364509,0.390018
153,Burundi,2.905,0.091623,0.151611,0.059901
154,Central African Republic,2.693,0.000000,0.018773,0.270842

In [6]:
happiness_metadata = pd.read_csv("data/happiness_report_metadata.csv", skiprows=3)  # CSV with metadata header
happiness_metadata

,country,happiness_score,GDP_per_capita,life_expectancy,freedom
0,Norway,7.537,1.616463,0.796667,0.635423
1,Denmark,7.522,1.482383,0.792566,0.626007
2,Iceland,7.504,1.480633,0.833552,0.627163
3,Switzerland,7.494,1.564980,0.858131,0.620071
4,Finland,7.469,1.443572,0.809158,0.617951
...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.326425,0.581844
151,Syria,3.462,0.777153,0.500533,0.081539
152,Tanzania,3.349,0.511136,0.364509,0.390018
153,Burundi,2.905,0.091623,0.151611,0.059901
154,Central African Republic,2.693,0.000000,0.018773,0.270842

In [7]:
happiness_xlsx = pd.read_excel("data/happiness_report.xlsx")    # Excel formatted data
happiness_xlsx

,country,happiness_score,GDP_per_capita,life_expectancy,freedom
0,Norway,7.537,1.616463,0.796667,0.635423
1,Denmark,7.522,1.482383,0.792566,0.626007
2,Iceland,7.504,1.480633,0.833552,0.627163
3,Switzerland,7.494,1.564980,0.858131,0.620071
4,Finland,7.469,1.443572,0.809158,0.617951
...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.326425,0.581844
151,Syria,3.462,0.777153,0.500533,0.081539
152,Tanzania,3.349,0.511136,0.364509,0.390018
153,Burundi,2.905,0.091623,0.151611,0.059901
154,Central African Republic,2.693,0.000000,0.018773,0.270842

In [8]:
happy_header = pd.read_csv("data/happiness_report_no_header.csv",   # CSV format without column headers
                           header=None,
                           names=["country",
                                  "happiness_score",
                                  "GDP_per_capita",
                                  "life_expectancy",
                                  "freedom"])
happy_header

,country,happiness_score,GDP_per_capita,life_expectancy,freedom
0,Norway,7.537,1.616463,0.796667,0.635423
1,Denmark,7.522,1.482383,0.792566,0.626007
2,Iceland,7.504,1.480633,0.833552,0.627163
3,Switzerland,7.494,1.564980,0.858131,0.620071
4,Finland,7.469,1.443572,0.809158,0.617951
...,...,...,...,...,...
150,Rwanda,3.471,0.368746,0.326425,0.581844
151,Syria,3.462,0.777153,0.500533,0.081539
152,Tanzania,3.349,0.511136,0.364509,0.390018
153,Burundi,2.905,0.091623,0.151611,0.059901
154,Central African Republic,2.693,0.000000,0.018773,0.270842

Visualize results

In [9]:
gdp_life_plot = alt.Chart(happy_header).mark_point().encode(    # Initialize chart as scatter plot (point) for happy_header df
    x=alt.X("GDP_per_capita").title("GDP contribution to Happiness Score"), # Set x axis as GPD per capita
    y=alt.Y("life_expectancy").title("Life expectancy contribution to Happiness Score") # Set y axis as life expectancy
).configure_axis(   # Set font sizes
    labelFontSize=12,
    titleFontSize=12
)
gdp_life_plot

alt.Chart(...)

In [10]:
happiness_bar = alt.Chart(happiness_metadata).mark_bar().encode(    # Initalize chart as bar chart for happiness_metadata df
    x=alt.X("happiness_score", bin=True),   # Set x axis as happiness score bins
    y=alt.Y("count()")  # Set y axis as counts of happiness scores per bin
).configure_axis(   # Set font sizes
    labelFontSize=12,
    titleFontSize=12
)
happiness_bar

alt.Chart(...)